### ISSUE TITLE
Cannot run binary on macOS 14 (Sonoma)

### ISSUE THREAD

**Issue by adsouza** [contour-terminal/contour#1421]
### Contour Terminal version

0.4.1.6292

### Installer source

GitHub: release page

### Operating System

macOS 14.1.2 (23B92)

### Architecture

ARM64

### Steps to reproduce

I installed the app & then tried to run it.

### Expected Behavior

I expected the app to start.

### Actual Behavior

“contour.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

### Additional notes

There's a workaround for this that I eventually discovered but is worth documenting:
Right-click on the app in Finder, select Open; a popup appears, at which you can choose to run it.
After that it'll start normally.

**Comment by christianparpart** [comment]
Hey @adsouza. I am on Apple M1 with MacOS Sonoma. If I remember correctly, you can still run the application by clicking somewhere on "Allow" within the permissions dialog of the system settings. @uspasojevic96 may maybe remember a bit better what the correct way was.

Other than that, I think, the only way to avoid users getting that dialog, is to pay Apple the fee to get a developer license to digitally sign the software with. That's it. - I tried it but failed, because it's apparently not that trivial. We want to have that eventually however. :)

**Comment by adsouza** [comment]
You're referring to disabling protection system wide. That's not necessary. The workaround I described is nice and granular. Maybe just add it to the installation instructions for macOS?

**Comment by christianparpart** [comment]
> The workaround I described is nice and granular. Maybe just add it to the installation instructions for macOS?

Oh that would be great. Thanks for the advice!

**Comment by uspasojevic96** [comment]
@adsouza its related to signing and gatekeeper, not SIP

@christianparpart buy the developer account and sign contour already

**Comment by christianparpart** [comment]
> @christianparpart buy the developer account and sign contour already

I actually tried, early last year, but failed in actually doing the signing procedure. In the end, it is our Github CI that must be able to sign the MacOS binary. I am actually open in paying that 80 bucks (or so) again (it sadly faded out just a week ago). Not sure if I'd be any better this time :)

**Comment by jobukkit** [comment]
> There's a workaround for this that I eventually discovered but is worth documenting:
Right-click on the app in Finder, select Open; a popup appears, at which you can choose to run it.
After that it'll start normally.

This is completely normal for apps from developers without a subscription, it's not a "workaround", it's how MacOS ensures you've verified the app is not a trojan. I would change the name of the issue to reflect that it's just a suggestion to the devs to get a subscription again.

**Comment by Yaraslaut** [comment]
@christianparpart i understand that this was resolved by now and we sign contours build for macos? maybe @uspasojevic96 you know?

**Comment by uspasojevic96** [comment]
Signing works now, but we have some other issue currently where it still cant validate file

**Comment by christianparpart** [comment]
but this might be due to my machine setup. I hope other can verify. On the other hand, maybe I can pull off my old x86-MacOS at some point and see how that one reacts on the newly signed build. :)

**Comment by dfallman** [comment]
I had the same issue when installing using brew just now. If you just open the binary after install you'll get a popup with no option to "Open" and no instructions for how to open. You have to right-click on the binary file (in `/Applications`) and select open there, and then a different popup says something similar except there's also an Open button :)

**Comment by christianparpart** [comment]
@dfallman @adsouza I have been getting some help in understanding and creating a profile on the Apple Developer platform and associated it with our application's signature. I do not know how long it will take, but soon (in theory), macOS should not complain anymore but straight open it. 🙏
