### ISSUE TITLE
Coredumps when drawing Unicode block characters

### ISSUE THREAD

**Issue by hackerb9** [contour-terminal/contour#424]
## Description

When attempting to draw box drawing characters, contour attempts to free() an invalid pointer and dumps core. 

## Environment

- Contour Version or Git commit hash: 2814f42f705756cd2dbaeb8579618801c714c7fd
- Operating System (name / distribution / version): Debian GNU/Linux 11
- Contour configuration: None
- TERM environment variable: xterm-256color
- Compiler version: g++ 10.2.1

## Steps to Reproduce

1. Install [ugrep](https://github.com/hackerb9/ugrep/)
2. Try running `ugrep 0..10FFFF` which will show every assigned unicode character. 
3. Eventually, Contour will crash

The point appears to be in the range of box drawing glyphs (U+2500) as I'm able to get it to coredump immediately when I type:

    ugrep box draw

____

Update: 

This does not crash:

    ugrep 2500..70

Nor does this:

    ugrep 2580..FF

But this crashes:

    ugrep 2570..F

**Comment by data-man** [comment]
Tested with embedded FT and HB (`-DCONTOUR_BUILD_WITH_EMBEDDED_FT_HB=ON`).
`ugrep box draw` - can't reproduce
`ugrep 2570..F` - can't reproduce

`$ ugrep 0..10FFFF > out` it's too long, so I interrupted it.

It will be very useful to know the versions of FreeType, HarfBuzz and UnicodeData.txt

**Comment by hackerb9** [comment]
That's interesting! Font rendering could be the issue. In particular, perhaps my machine is using a corrupt font for just those characters. The weird thing is that it doesn't affect any other terminals. I'm using FreeType 2.10.4:

> $ apt policy libfreetype6-dev
> libfreetype6-dev:
>   Installed: 2.10.4+dfsg-1
>   Candidate: 2.10.4+dfsg-1
>   Version table:
>  *** 2.10.4+dfsg-1 500
>         500 http://deb.debian.org/debian bullseye/main amd64 Packages
>         100 /var/lib/dpkg/status
> 

I just tried XTerm (which is linked with the same version of FreeType) and it had no issue. It is not linked with harfbuzz, though. My harfbuzz is 2.7.4-1. 

> $ apt policy libharfbuzz-dev
> libharfbuzz-dev:
>   Installed: 2.7.4-1
>   Candidate: 2.7.4-1
>   Version table:
>  *** 2.7.4-1 500
>         500 http://deb.debian.org/debian bullseye/main amd64 Packages
>         100 /var/lib/dpkg/status

My UnicodeData.txt is version 13.0.0, but I'm pretty sure that is unrelated.

____

So, I ran it under a debugger and have narrowed the crash down to src/terminal_renderer/BoxDrawingRenderer.cpp:512. The name of the file implies Contour is treating box drawing characters special, which leads me to think the problem is not in FreeType, HarfBuzz, or UnicodeData.txt.


<details><summary>gdb</summary>

```gdb
(gdb) run
Starting program: src/contour/src/contour/contour 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[error] Superfluous config key found: profiles.main.font.regular
[error] Superfluous config key found: profiles.main.hyperlink_decoration.default
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[New Thread 0x7ffff2a48700 (LWP 530358)]
[New Thread 0x7ffff0e9f700 (LWP 530359)]
[New Thread 0x7ffff069e700 (LWP 530360)]
[New Thread 0x7fffefe66700 (LWP 530361)]
[New Thread 0x7fffef64f700 (LWP 530362)]
[New Thread 0x7fffeec31700 (LWP 530363)]
[New Thread 0x7fffee430700 (LWP 530365)]
[Detaching after fork from child process 530366]
[New Thread 0x7fffed82e700 (LWP 530367)]
[New Thread 0x7fffebe20700 (LWP 530369)]
[New Thread 0x7fffe328f700 (LWP 530370)]
[New Thread 0x7fffe294d700 (LWP 530371)]
[New Thread 0x7fffe214c700 (LWP 530372)]
[New Thread 0x7fffe194b700 (LWP 530373)]
[New Thread 0x7fffe114a700 (LWP 530374)]
[New Thread 0x7fffe0949700 (LWP 530375)]
[New Thread 0x7fffe0148700 (LWP 530376)]
[New Thread 0x7fffdf947700 (LWP 530377)]
[New Thread 0x7fffdf146700 (LWP 530378)]
[New Thread 0x7fffde945700 (LWP 530379)]
[New Thread 0x7fffde144700 (LWP 530380)]
[New Thread 0x7fffdd943700 (LWP 530381)]
[New Thread 0x7fffdd142700 (LWP 530382)]
[New Thread 0x7fffdc941700 (LWP 530383)]
[New Thread 0x7fffdc140700 (LWP 530384)]
[New Thread 0x7fffdb93f700 (LWP 530385)]
[New Thread 0x7fffdb13e700 (LWP 530386)]
[New Thread 0x7fffda93d700 (LWP 530387)]
[New Thread 0x7fffda13c700 (LWP 530388)]
[New Thread 0x7fffd993b700 (LWP 530389)]
[New Thread 0x7fffd913a700 (LWP 530390)]
[New Thread 0x7fffd8939700 (LWP 530391)]
[New Thread 0x7fffd8138700 (LWP 530392)]
[New Thread 0x7fffd7937700 (LWP 530393)]
[New Thread 0x7fffd7136700 (LWP 530394)]
[New Thread 0x7fffd6935700 (LWP 530395)]
[New Thread 0x7fffd6134700 (LWP 530396)]
[New Thread 0x7fffd5933700 (LWP 530397)]
[New Thread 0x7fffd5132700 (LWP 530398)]
[New Thread 0x7fffd4931700 (LWP 530399)]
[New Thread 0x7fffd4130700 (LWP 530400)]
[New Thread 0x7fffd392f700 (LWP 530401)]
[New Thread 0x7fffd312e700 (LWP 530402)]
[New Thread 0x7fffd292d700 (LWP 530403)]
[New Thread 0x7fffd212c700 (LWP 530404)]
[New Thread 0x7fffd192b700 (LWP 530405)]
[New Thread 0x7fffd112a700 (LWP 530406)]
[New Thread 0x7fffd0929700 (LWP 530407)]
[New Thread 0x7fffd0128700 (LWP 530408)]
[New Thread 0x7fffcf527700 (LWP 530409)]
[New Thread 0x7fffce8db700 (LWP 530410)]
[New Thread 0x7fffcd3e6700 (LWP 530411)]
free(): invalid pointer

Thread 1 "contour" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff649d537 in __GI_abort () at abort.c:79
#2  0x00007ffff64f6768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6604e2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff64fda5a in malloc_printerr (str=str@entry=0x7ffff660305a "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff64ffca6 in free_check (mem=0x1b1cb10, caller=<optimized out>) at hooks.c:255
#5  0x000000000056e450 in __gnu_cxx::new_allocator<unsigned char>::deallocate(unsigned char*, unsigned long)
    (__t=<optimized out>, __p=<optimized out>, this=0x7fffffffcd80) at /usr/include/c++/10/ext/new_allocator.h:133
#6  std::allocator_traits<std::allocator<unsigned char> >::deallocate(std::allocator<unsigned char>&, unsigned char*, unsigned long)
    (__n=<optimized out>, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:492
#7  std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_deallocate(unsigned char*, unsigned long)
    (__n=<optimized out>, __p=<optimized out>, this=0x7fffffffcd80) at /usr/include/c++/10/bits/stl_vector.h:354
#8  std::_Vector_base<unsigned char, std::allocator<unsigned char> >::~_Vector_base() (this=0x7fffffffcd80, __in_chrg=<optimized out>)
    at /usr/include/c++/10/bits/stl_vector.h:335
#9  std::vector<unsigned char, std::allocator<unsigned char> >::~vector() (this=0x7fffffffcd80, __in_chrg=<optimized out>)
    at /usr/include/c++/10/bits/stl_vector.h:683
#10 std::_Optional_payload_base<std::vector<unsigned char, std::allocator<unsigned char> > >::_M_destroy() (this=0x7fffffffcd80)
    at /usr/include/c++/10/optional:260
#11 std::_Optional_payload_base<std::vector<unsigned char, std::allocator<unsigned char> > >::_M_reset() (this=0x7fffffffcd80)
    at /usr/include/c++/10/optional:280
#12 std::_Optional_payload<std::vector<unsigned char, std::allocator<unsigned char> >, false, false, false>::~_Optional_payload()
    (this=0x7fffffffcd80, __in_chrg=<optimized out>) at /usr/include/c++/10/optional:401
#13 std::_Optional_base<std::vector<unsigned char, std::allocator<unsigned char> >, false, false>::~_Optional_base()
    (this=0x7fffffffcd80, __in_chrg=<optimized out>) at /usr/include/c++/10/optional:474
#14 std::optional<std::vector<unsigned char, std::allocator<unsigned char> > >::~optional() (this=0x7fffffffcd80, __in_chrg=<optimized out>)
    at /usr/include/c++/10/optional:659
#15 terminal::renderer::BoxDrawingRenderer::getDataRef(unsigned char) (this=0x80c5c8, _id=113 'q')
    at src/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:512
#16 0x000000000056e83b in terminal::renderer::BoxDrawingRenderer::render(crispy::boxed<int, terminal::detail::tags::LinePosition>, crispy::boxed<int, terminal::detail::tags::Column>, unsigned char, terminal::RGBColor) (this=this@entry=0x80c5c8, _line=..., _column=..., _id=<optimized out>, _color=...)
    at src/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:456
#17 0x000000000057b635 in terminal::renderer::TextRenderer::renderCell(terminal::RenderCell const&) (this=this@entry=0x80c540, _cell=...)
    at src/contour/src/terminal_renderer/TextRenderer.cpp:137
#18 0x00000000005751ea in terminal::renderer::Renderer::renderCells(std::vector<terminal::RenderCell, std::allocator<terminal::RenderCell> > const&)
    (this=this@entry=0x80c278, _renderableCells=<optimized out>) at src/contour/src/terminal_renderer/Renderer.cpp:340
#19 0x0000000000575341 in terminal::renderer::Renderer::render(terminal::Terminal&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, bool) (this=this@entry=0x80c278, _terminal=..., _now=..., _pressure=_pressure@entry=false)
    at src/contour/src/terminal/RenderBuffer.h:61
#20 0x0000000000561307 in contour::opengl::TerminalWidget::paintGL() (this=0x80c1f0) at src/contour/src/contour/opengl/TerminalWidget.cpp:449
#21 0x00007ffff7951c5d in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff7933fae in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x0000000000564ea8 in contour::opengl::TerminalWidget::event(QEvent*) (this=0x80c1f0, _event=0x7fffffffd140)
    at src/contour/src/contour/opengl/TerminalWidget.cpp:571
#24 0x00007ffff78f415f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff6c17fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff792c116 in QWidgetPrivate::sendPaintEvent(QRegion const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff7904ba8 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff79346d7 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff78f415f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff6c17fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6c1aa01 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6c6fe93 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff62dae6b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff62db118 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff62db1cf in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff6c6f51f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff6c1698b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007ffff6c1ec00 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00000000004d6a09 in contour::terminalGUI(int, char const**, crispy::cli::FlagStore const&) (argc=<optimized out>, argv=0x7fffffffe638, _flags=...) at src/contour/src/contour/ContourGuiApp.cpp:188
#40 0x0000000000581edd in std::function<int ()>::operator()() const (this=0x668230) at /usr/include/c++/10/bits/std_function.h:622
#41 crispy::App::run(int, char const**) (this=this@entry=0x7fffffffe360, argc=argc@entry=1, argv=argv@entry=0x7fffffffe638) at src/contour/src/crispy/App.cpp:242
#42 0x00000000004d4852 in contour::ContourGuiApp::run(int, char const**) (this=this@entry=0x7fffffffe360, argc=argc@entry=1, argv=argv@entry=0x7fffffffe638) at src/contour/src/contour/ContourGuiApp.cpp:52
#43 0x000000000048e7fb in main(int, char const**) (argc=1, argv=0x7fffffffe638) at src/contour/src/contour/main.cpp:24
(gdb) up
#1  0x00007ffff649d537 in __GI_abort () at abort.c:79
79      abort.c: No such file or directory.
(gdb) 
#2  0x00007ffff64f6768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6604e2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
155     ../sysdeps/posix/libc_fatal.c: No such file or directory.
(gdb) 
#3  0x00007ffff64fda5a in malloc_printerr (str=str@entry=0x7ffff660305a "free(): invalid pointer") at malloc.c:5347
5347    malloc.c: No such file or directory.
(gdb) 
#4  0x00007ffff64ffca6 in free_check (mem=0x1b1cb10, caller=<optimized out>) at hooks.c:255
255     hooks.c: No such file or directory.
(gdb) 
#5  0x000000000056e450 in __gnu_cxx::new_allocator<unsigned char>::deallocate (__t=<optimized out>, __p=<optimized out>, this=0x7fffffffcd80)
    at /usr/include/c++/10/ext/new_allocator.h:133
133             ::operator delete(__p
(gdb) 
#6  std::allocator_traits<std::allocator<unsigned char> >::deallocate (__n=<optimized out>, __p=<optimized out>, __a=...)
    at /usr/include/c++/10/bits/alloc_traits.h:492
492           { __a.deallocate(__p, __n); }
(gdb) 
#7  std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_deallocate (__n=<optimized out>, __p=<optimized out>, this=0x7fffffffcd80)
    at /usr/include/c++/10/bits/stl_vector.h:354
354               _Tr::deallocate(_M_impl, __p, __n);
(gdb) 
#8  std::_Vector_base<unsigned char, std::allocator<unsigned char> >::~_Vector_base (this=0x7fffffffcd80, __in_chrg=<optimized out>)
    at /usr/include/c++/10/bits/stl_vector.h:335
335             _M_deallocate(_M_impl._M_start,
(gdb) 
#9  std::vector<unsigned char, std::allocator<unsigned char> >::~vector (this=0x7fffffffcd80, __in_chrg=<optimized out>)
    at /usr/include/c++/10/bits/stl_vector.h:683
683           }
(gdb) 
#10 std::_Optional_payload_base<std::vector<unsigned char, std::allocator<unsigned char> > >::_M_destroy (this=0x7fffffffcd80)
    at /usr/include/c++/10/optional:260
260             _M_payload._M_value.~_Stored_type();
(gdb) 
#11 std::_Optional_payload_base<std::vector<unsigned char, std::allocator<unsigned char> > >::_M_reset (this=0x7fffffffcd80) at /usr/include/c++/10/optional:280
280               _M_destroy();
(gdb) 
#12 std::_Optional_payload<std::vector<unsigned char, std::allocator<unsigned char> >, false, false, false>::~_Optional_payload (this=0x7fffffffcd80, 
    __in_chrg=<optimized out>) at /usr/include/c++/10/optional:401
401           ~_Optional_payload() { this->_M_reset(); }
(gdb) 
#13 std::_Optional_base<std::vector<unsigned char, std::allocator<unsigned char> >, false, false>::~_Optional_base (this=0x7fffffffcd80, 
    __in_chrg=<optimized out>) at /usr/include/c++/10/optional:474
474         struct _Optional_base
(gdb) up
#14 std::optional<std::vector<unsigned char, std::allocator<unsigned char> > >::~optional (this=0x7fffffffcd80, __in_chrg=<optimized out>)
    at /usr/include/c++/10/optional:659
659         class optional
(gdb) 
#15 terminal::renderer::BoxDrawingRenderer::getDataRef (this=0x80c5c8, _id=113 'q') at src/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:512
512             auto tmp = build(_id, gridMetrics_.cellSize, gridMetrics_.underline.thickness);
(gdb) list 500,524
500             }();
501             auto const supersamplingSize = gridMetrics_.cellSize * supersamplingFactor;
502             auto const supersamplingLineThickness = gridMetrics_.underline.thickness * 2;
503             auto tmp = build(_id, supersamplingSize, supersamplingLineThickness);
504             if (!tmp)
505                 return nullopt;
506
507             //buffer = downsample(*tmp, gridMetrics_.cellSize, supersamplingFactor);
508             buffer = downsample(*tmp, 1, supersamplingSize, gridMetrics_.cellSize);
509         }
510         else
511         {
512             auto tmp = build(_id, gridMetrics_.cellSize, gridMetrics_.underline.thickness);
513             if (!tmp)
514                 return nullopt;
515             buffer = move(*tmp);
516         }
517
518         return textureAtlas_->insert(
519             _id,
520             gridMetrics_.cellSize,
521             gridMetrics_.cellSize,
522             move(buffer)
523         );
524     }
(gdb) up
#16 0x000000000056e83b in terminal::renderer::BoxDrawingRenderer::render (this=this@entry=0x80c5c8, _line=..., _column=..., _id=<optimized out>, _color=...)
    at src/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:456
456         auto data = getDataRef(_id);
(gdb) down
#15 terminal::renderer::BoxDrawingRenderer::getDataRef (this=0x80c5c8, _id=113 'q') at src/contour/src/terminal_renderer/BoxDrawingRenderer.cpp:512
512             auto tmp = build(_id, gridMetrics_.cellSize, gridMetrics_.underline.thickness);
(gdb) p _id
$6 = 113 'q'
(gdb) p gridMetrics_ .cellSize 
$7 = {
  width = {
    value = 10
  },
  height = {
    value = 19
  }
}
(gdb) p gridMetrics_.underline.
position   thickness  
(gdb) p gridMetrics_.underline.thickness 
$8 = 2

```

**Comment by christianparpart** [comment]
Holy weck? You can disable built-in box drawing per config. But that should be fixed ASAP. Thanks.

**Comment by christianparpart** [comment]
Note, I was trying to reproduce your box drawing crash but I couldn't. I think this bug report in general is about two things (right?)

- [ ] box drawing crash (at least on your side)
- [x] `ugrep 0..10FFF` will crash (reason known, fix is available in my WIP `grid` branch.

While the latter I think i cannot add into a bugfix release (0.2.1) the other one I try to fix within this ticket for 0.2.1. 
I'm currently on OS/X, will be trying to reproduce the box drawing crash on Linux.

**Comment by hackerb9** [comment]
I had intended this bug report to only be for the box drawing crash. I did not know about the other bug. 

By the way, I checked out the improvement/grid branch and I still get "free(): invalid pointer" at BoxDrawingRenderer.cpp:512 when showing the box drawing characters (`ugrep box draw`).

**Comment by dankamongmen** [comment]
i am seeing a similar `minmap_chunk(): invalid pointer` SIGABRT when running `notcurses-info` in current contour, and have been for a minute:

```
[schwarzgerat](0) $ contour
[error] Superfluous config key found: scrollbar.position
[error] Superfluous config key found: scrollbar.hide_in_alt_screen
[error] Superfluous config key found: scrollbar
[error] Superfluous config key found: profiles.main.font.only_monospace
[error] Superfluous config key found: profiles.main.tab_width
[error] Superfluous config key found: profiles.main.hyperlink_decoration.default
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1271] Unknown VT sequence: CSI > u
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1271] Unknown VT sequence: CSI = 1 u
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1271] Unknown VT sequence: CSI ? u
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1304] Unsupported VT sequence: CSI = c
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1301] Invalid VT sequence: CSI ? 8452 h
[vt.parser:dankamongmen/contour/src/terminal/Sequencer.cpp:1304] Unsupported VT sequence: CSI > 1 s
munmap_chunk(): invalid pointer
Aborted (core dumped)
[schwarzgerat](134) $ 
```

**Comment by christianparpart** [comment]
> i am seeing a similar minmap_chunk(): 

I need more unit tests. I think that is the next ticket i gonna tackle.

**Comment by christianparpart** [comment]
Talking to my very self here: I could repro it, thanks to godlike notcurses-info :)

![image](https://user-images.githubusercontent.com/56763/135722046-e1023a54-d3d5-4103-bef5-624350baddb4.png)

it's all about my crappy box drawing. will locate and fix it.

**Comment by christianparpart** [comment]
> `$ ugrep 0..10FFFF > out` it's too long, so I interrupted it.

@data-man reason for the "too long" is that current glyph and text cache is an `unordered_map`. That has changed in the grid branch to an LRU cache (on many places). But branch sadly isn't ready yet (due to other reasons).

> It will be very useful to know the versions of FreeType, HarfBuzz and UnicodeData.txt

**Comment by dankamongmen** [comment]
freetype: 2.10.4+dfsg-1
harfbuzz: 2.7.4-1
unicode-data: 14.0.0-1

standard debian unstable

**Comment by christianparpart** [comment]
Meh. It is most likely nothing to do with FT or HB. But thanks. 💟

**Comment by christianparpart** [comment]
@dankamongmen if you check out the above branch from #436 then `notcurses-info` at least does not SEGV for me anymore. thanks to your awesome project I keep hardening my code :+1:

@hackerb9 not sure this will also satisfy your bug report, I hope so. so maybe you want to give that branch a test as well?

On the other hand, I'll be merging that fix for sure into master, so if you don't read me within the next 5 minutes, you can as well just test latest `master` :-)

Happy hacking.

**Comment by dankamongmen** [comment]
@christianparpart confirmed fix for `notcurses-info`, thanks!

btw i saw some comments about line/box drawing; if you get those sextants done, let me know, so i can credit contour with 3x2 cell blitting.

**Comment by christianparpart** [comment]
> @christianparpart confirmed fix for `notcurses-info`, thanks!
> 
> btw i saw some comments about line/box drawing; if you get those sextants done, let me know, so i can credit contour with 3x2 cell blitting.

Are you referring to #419 (especially [this](https://www.unicode.org/charts/PDF/U2580.pdf)) Help me catching up, please :)

**Comment by dankamongmen** [comment]
https://www.unicode.org/charts/PDF/U2580.pdf is the new eighths cells. i use them for plots. i refer to 1FB00 through 1FB3B. here's a screenshot of `notcurses-info` in kitty, with the sextants circled:

![2021-10-02-151147_940x727_scrot](https://user-images.githubusercontent.com/143473/135729194-a4cfc0aa-ab71-4e93-8ed4-bc66ec48fc42.png)

yours are probably using the font, and look much less tidy.

**Comment by dankamongmen** [comment]
btw the kitty/foot renderings are pretty much the reference renderings

**Comment by dankamongmen** [comment]
here's what i see for you

![contour](https://user-images.githubusercontent.com/143473/135729292-ab8ccce0-d1f4-41c1-b1e7-d2e7eda5a6f1.png)

**Comment by christianparpart** [comment]
@dankamongmen let me do that pixel-perfect for you, let me make you happy ;-)

**Comment by christianparpart** [comment]
> i refer to 1FB00 through 1FB3B. here's a screenshot of notcurses-info in kitty

For 2580..2590 I have just implemented (see draft PR linked above). The rest will follow.

BUT I just realized that the emoji line in kitty looks evenly spaced. But how's that possible when the codepoint's width is not alwasy 2 but 1 for a few. I currently strictly obey to EA width. Do you do anything different or is this kitty? (p.s.: there's a draft spec to have those oddities sorted out in https://github.com/contour-terminal/terminal-unicode-core that I want to push for soon - I just need to eat and sleep first though :) )

**Comment by christianparpart** [comment]
I think this one is fixed now. Ideally @hackerb9 would confirm it for his case. But i'm closing as I'm pretty confident it is. :-)

**Comment by dankamongmen** [comment]
> BUT I just realized that the emoji line in kitty looks evenly spaced. But how's that possible when the codepoint's width is not alwasy 2 but 1 for a few. I currently strictly obey to EA width. Do you do anything different or is this kitty? (p.s.: there's a draft spec to have those oddities sorted out in https://github.com/contour-terminal/terminal-unicode-core that I want to push for soon - I just need to eat and sleep first though :) )

kitty does all kinds of crap under the hood regarding wide chars, which you can find in its docs (don't have time to pull it up atm sorry). others draw everything a single column wide. emoji are kind of a crapshoot. i have some ideas regarding how to deal with them better, but it's notcurses 4 material.

wezterm recently changed how it did emoji and they look awesome there.

**Comment by christianparpart** [comment]
I am all open for your feedback on the above unicode cute proposal that i drafted.

It isn't hard to implement but gives us some beers good guarantees that were undefined since ever. So far i only got (constructive)positive feedback from jerch and j4james, but i did not ask a library/app devs yet. Maybe see #404 :)

**Comment by data-man** [comment]
@christianparpart 

> reason for the "too long" is that current glyph and text cache is an unordered_map.

It's slow in any terminal. :)

> It is most likely nothing to do with FT or HB.

I asked about the versions because support Unicode 14.0 was only added to HarfBuzz 3.0.

**Comment by hackerb9** [comment]
> I think this one is fixed now. Ideally @hackerb9 would confirm it for his case. But i'm closing as I'm pretty confident it is. :-)

Yup, you fixed it!

[Sorry for the delay. I hadn't been able to recompile contour as cmake's package manager was hanging on trying to install catch2. I gave up on trying to figure out why and just did an `apt install catch2; git clean -f` and now all is well.]

**Comment by christianparpart** [comment]
> > I think this one is fixed now. Ideally @hackerb9 would confirm it for his case. But i'm closing as I'm pretty confident it is. :-)
> 
> Yup, you fixed it!
> 
> [Sorry for the delay. I hadn't been able to recompile contour as cmake's package manager was hanging on trying to install catch2. I gave up on trying to figure out why and just did an `apt install catch2; git clean -f` and now all is well.]

@data-man This is due to the CPM related dependency updates. Is this a CPM thingy or is there any way to mitigate this? I keep having the same issue and it sometimes drives me nuts 

Can you add some leading space(s) in front of your ugrep lines. This is sometimes so unreadable. Also fonttable would be nice to accept a list of ranges of Codepoints that i want it to print. Do you want me to create a ticket for these?

**Comment by hackerb9** [comment]
Yes, please create tickets. I'm not clear on what the readability problem is.

**Comment by data-man** [comment]
@christianparpart 
I think the built-in tests should be disabled in all third-party libraries. I'll check.

**Comment by hackerb9** [comment]
@data-man I didn't have Catch2 installed before and didn't have the problem until suddenly I did. I'm not sure what I did differently, perhaps `make clean` after a git pull? Except I'm sure that's worked before. Also, something in the CPM cache was stubbornly stuck and I had to nuke it to get cmake to recognize my system now has Catch2.

Is there a way people can disable CPM and instead simply list any missing libraries? (Besides this weird error, I prefer using libraries my distribution's security team has vetted.)

**Comment by data-man** [comment]
@hackerb9 How do you compile Contour?
Unit tests are enabled by default. Please try with `-DCONTOUR_TESTING=OFF`.

@christianparpart
> I think it isn't a too bad idea to first check via find_package()

We use Catch2 **v3**. I doubt this version exists in all popular OS repositories.

**Comment by hackerb9** [comment]
> @hackerb9 How do you compile Contour? Unit tests are enabled by default. Please try with `-DCONTOUR_TESTING=OFF`.

I'm building with:

    cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO .  &&  make -j

It's compiling fine at the moment , but I'll try turning off unit tests if it gives me more guff. 
 
> We use Catch2 **v3**. I doubt this version exists in all popular OS repositories.

Oh, I see that you are correct. Cmake was ignoring the system version of catch2 I had installed. I guess the `git` clean -f` was what cmake needed to be able to get past whatever was hanging up CPM.
