### ISSUE TITLE
When highlighting a word with mouse, the actual highlight location is not visible, only other occurrences (if they exist)

### ISSUE THREAD

**Issue by whisperity** [contour-terminal/contour#930]
### Contour Terminal version

0.3.9.4459

### Installer source

Github: CI actions

### Operating System

Ubuntu 20.04 & 22.04

### Architecture

x86-64

### Other Software

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Steps to reproduce

1. `echo foo`
2. Double-click `foo` (in the `echo` line) to highlight
3. The echoed output is highlighted (background inverted), but the actual clicked word is not.

Here I clicked `zsh` in the **fourth** line.
![Screenshot_20221220_125150](https://user-images.githubusercontent.com/1969470/208660677-6d14a38b-8fd0-4b4e-951d-e7411af35320.png)

Highlighting a longer line is even worse. Here, I started clicking the line from `sudo` and onwards to copy the entire command (I needed to run this on 4 different machines...), and this was the visual effect produced:
![Screenshot_20221220_125435](https://user-images.githubusercontent.com/1969470/208661271-f8fb21ae-9ab3-4a34-bf0a-ee3a5b6b915b.png)

### Expected Behavior

The primary occurrence, where I am clicking and highlighting, should be highlighted. Perhaps to not make it this distracting, *other* occurrences in the buffer should receive a **different** highlight...

**Comment by christian-parpart-frequenz** [comment]
Um, but for me it's working, I use that basically daily. Is this maybe due to what color is chosen? hmm.

**Comment by christianparpart** [comment]
Um, but for me it's working, I use that basically daily. Is this maybe due to what color is chosen? hmm.

**Comment by whisperity** [comment]
There is no colour choice done by me to the best of my understanding. Note that `zsh`, where "green-on-black" originally in a prompt, gets inverted as "black-on-green". In every other place, the "white-on-black" words get inverted with "black-on-white" **except** for the mouse highlight.

**Comment by christianparpart** [comment]
okay, to clarify. this is probably some limitation in how it is implemented as of right now. I certainly want to improve here, because I think this feature is in fact kinda handy (to me at least).

Currently match highlighting only works on word-selection (double clicked words).
If you extend that selection to more words, the match-highlights will remain on the initial word.

The other thing (that your match isn't highlighted), is obviously a bug and I can only guess why for now (i'll digg deeper later).

Generally however, we could extend this functionality to any selection (not just double-clicked words).

**Comment by whisperity** [comment]
I'm not trying to argue the merit of the feature here (and in fact, I also do like the general idea). But why is the highlight "removed" (or not applied) to the initially clicked word?

Could we instead use a separate highlight for "searches" instead of "just inverting the background"? That would make it explicit that the highlight is happening **precisely because of** the search action.

If you tell me which configuration values would affect the result I can show them from the config. Because even by using the default:

Original contents: ![Screenshot_20221221_113101](https://user-images.githubusercontent.com/1969470/208884050-fbc232d9-3f54-47a1-890c-bc64c63cd174.png)

After double-click on the first `foo`:  ![Screenshot_20221221_113107](https://user-images.githubusercontent.com/1969470/208884092-70058861-8943-4539-bdc6-275259d2fc1c.png)

After double click, dragging the mouse to highlight the second `foo`: ![Screenshot_20221221_113116](https://user-images.githubusercontent.com/1969470/208884135-d87d81aa-84c9-43d4-afff-fb8061bf20e3.png)

This last part is the one that I find rather misleading. I see two "random" `foo`s (foo no. 3 and 4) highlighted, and a space (???) highlighted. Without consciously being aware of the thing, now I have no idea what I highlighted, what I am about to copy (into another prompt, for example).

Even if we could somehow catch the "mouse dragged while left button is pressed" action and just decide to throw the highlighting away, that could help this.

**Comment by cqexbesd** [comment]
Randomly guessing, re your question about config items.

> Could we instead use a separate highlight for "searches" instead of "just inverting the background"?

`color_schemes.search_highlight` could be used for that right? and `color_schemes.search_highlight_focussed` for the current match.

I don't see the current match highlighted in your screen shots - maybe you have it set to the same scheme as the other highlights so its not visually apparent? Maybe the un-highlighted one is actually the focused one and the colour scheme is set so its hard to tell?

Perhaps try changing the respective settings to bright unique colours in your colour scheme so its obvious what each match is categorised as?

Like Christian I can't reproduce, even using your exact commands. If you don't get anywhere with changing the colour scheme then maybe post the colour section of your config?

**Comment by whisperity** [comment]
Looks like it was fixed and after upgrading Contour sufficiently (right now I'm on version 0.3.10.4591) it seems to work.

We really should have a mechanism that fills in good defaults and warns about the config being out of date and a key inherited from built-in defaults or something like that...

#776

**Comment by mathias-baumann-frequenz** [comment]
Well, I am on 0.3.10-master-2532adfe and have the same problem still..

**Comment by mathias-baumann-frequenz** [comment]
Regarding why the bug happens: My suspicion is that you basically "flip" the colors twice. One time for the click and one time for highlighting all the words in the buffer.

**Comment by christianparpart** [comment]
Oh I did not add its own color group für that just yet. Thanks for the reminder. Will do...
