### ISSUE TITLE
[Regression] On macOS, home directory and initial_working_directory don't work

### ISSUE THREAD

**Issue by uspasojevic96** [contour-terminal/contour#946]
### Contour Terminal version

0.3.8.247

### Installer source

GitHub: release page

### Operating System

macOS Monterey 12.6.2

### Architecture

x86-64

### Steps to reproduce

- Download .dmg
- Open .dmg
- Copy contour.app to /Applications
- Run contour.app from /Applications

### Expected Behavior

Shell should be spawned in $HOME

### Actual Behavior

Shell is spawned in /

### Additional notes

Default contour config

**Comment by christianparpart** [comment]
Should be fixed through #948. Would you mind giving it a try?

**Comment by uspasojevic96** [comment]
Will try when I get access to his laptop, so either later tonight or tomorrow morning

**Comment by uspasojevic96** [comment]
Fixed

**Comment by andrewstonedev** [comment]
This issue seems to still exist on 0.3.9.250 (installed today)

**Comment by christianparpart** [comment]
Hey. Oh I think we fixed that on master. Let me verify and we should probably release asap.

**Comment by uspasojevic96** [comment]
On master it's fixed but we didn't do any new release I think

**Comment by andrewstonedev** [comment]
yeah that would probably do it. I didn't look close enough at the date when #948 was committed (December 24). it says 0.3.9.250 released "a months ago" so I'll take that to me 30+ days. Not really an issue anyway, just a 2 second inconvenience at worst
